name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish-docker:
    name: "Publish Docker image to DockerHub"
    if: github.event_name == 'push' && github.repository == 'Veridise/picus-private'
    env:
      IMAGE_TAG: git-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SAAS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SAAS_DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64
          tags: veridise/picus:git-latest, veridise/picus:git-${{ github.sha }}
