name: Full test

on: [push, workflow_dispatch]

jobs:
  configuration-test:
    runs-on: ubuntu-latest
    container:
      image: veridise/picus:git-latest
    env:
      PLTADDONDIR: /root/.local/share/racket/
    steps:
      - uses: actions/checkout@v1
      - name: linking circom
        run: ln -s /root/.cargo/bin/circom /usr/bin/circom
      - name: compile circomlib
        run: bash ./scripts/prepare-circomlib.sh

      - name: unsafe test cvc5 solver
        uses: ./.github/workflows/config-test
        with:
          param: --solver cvc5 ./benchmarks/circomlib-cff5ab6/Decoder@multiplexer.circom
          exit: 9
      - name: unsafe test z3 solver
        uses: ./.github/workflows/config-test
        with:
          param: --solver z3 ./benchmarks/circomlib-cff5ab6/Decoder@multiplexer.circom
          exit: 9
      - name: unsafe test circom format with opt-level 2
        uses: ./.github/workflows/config-test
        with:
          param: --opt-level 2 ./benchmarks/circomlib-cff5ab6/Decoder@multiplexer.circom
          exit: 9
      - name: unsafe test r1cs format
        uses: ./.github/workflows/config-test
        with:
          param: ./benchmarks/circomlib-cff5ab6/Decoder@multiplexer.r1cs
          exit: 9
      - name: unsafe test sr1cs format
        uses: ./.github/workflows/config-test
        with:
          param: ./tests/sr1cs/unsafe.sr1cs
          exit: 9

      - name: safe test cvc5 solver
        uses: ./.github/workflows/config-test
        with:
          param: --solver cvc5 ./benchmarks/circomlib-cff5ab6/AND@gates.circom
          exit: 8
      - name: safe test z3 solver
        uses: ./.github/workflows/config-test
        with:
          param: --solver z3 ./benchmarks/circomlib-cff5ab6/AND@gates.circom
          exit: 8
      - name: safe test circom format with opt-level 2
        uses: ./.github/workflows/config-test
        with:
          param: --opt-level 2 ./benchmarks/circomlib-cff5ab6/AND@gates.circom
          exit: 8
      - name: safe test r1cs format
        uses: ./.github/workflows/config-test
        with:
          param: ./benchmarks/circomlib-cff5ab6/AND@gates.r1cs
          exit: 8
      - name: safe test sr1cs format
        uses: ./.github/workflows/config-test
        with:
          param: ./tests/sr1cs/safe.sr1cs
          exit: 8

      - name: generate witness files
        uses: ./.github/workflows/config-test
        with:
          param: --wtns . ./benchmarks/circomlib-cff5ab6/Decoder@multiplexer.circom
          exit: 9
      - name: test witness files
        run: |
          diff first-witness.wtns tests/data/first-witness.wtns.expect
          diff second-witness.wtns tests/data/second-witness.wtns.expect

  misc-test:
    runs-on: ubuntu-latest
    container:
      image: veridise/picus:git-latest
    env:
      PLTADDONDIR: /root/.local/share/racket/
    steps:
      - uses: actions/checkout@v1
      - name: run tests
        run: |
          raco test ./tests/performance-test.rkt
          raco test ./tests/framework-test.rkt

  main-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: circomlib
            num-runs: 3
            jobs: '[0, 1, 2]'
            path: ./tests/circomlib-test.rkt
          - name: mixed
            num-runs: 1
            jobs: '[0]'
            path: ./tests/mixed-test.rkt
    uses: ./.github/workflows/main-test.yml
    with:
      name: ${{ matrix.name }}
      num-runs: ${{ matrix.num-runs }}
      jobs: ${{ matrix.jobs }}
      path: ${{ matrix.path }}
