name: Release

on:
    pull_request:
        types:
          - opened
          - reopened
    pull_request_review:
        types: 
          - submitted
        
 
jobs:
  call-workflow-release:
    uses: Veridise/release_helpers/.github/workflows/release.yml@main
    secrets: inherit